/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aggoun.gestion1;

import com.aggoun.gestion1.DB.DataBase;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Dual Computer
 */
public class Situationclient extends javax.swing.JFrame {

    /**
     * Creates new form Situationclient
     */
    DataBase db = new DataBase();
    public Situationclient() throws SQLException {
        initComponents();
        db.ConnectionToDataBase(); 
        parametre();
    }
    private void parametre() throws SQLException{
        CBX_CLIENT.removeAllItems();
        db.getAllClient(CBX_CLIENT);
         DefaultTableCellRenderer centre = new DefaultTableCellRenderer();
        centre.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        for (int i=0;i<7;i++){
            TABLE_SITUATION.getColumnModel().getColumn(i).setCellRenderer(centre);
        } 
        TABLE_SITUATION.setRowHeight(30);
        TableColumnModel colummodel= TABLE_SITUATION.getColumnModel();
        colummodel.getColumn(0).setPreferredWidth(80);
        colummodel.getColumn(1).setPreferredWidth(40);
        colummodel.getColumn(2).setPreferredWidth(80);
        colummodel.getColumn(3).setPreferredWidth(80);
        colummodel.getColumn(4).setPreferredWidth(40);
        colummodel.getColumn(5).setPreferredWidth(80);
        colummodel.getColumn(6).setPreferredWidth(80);
       
        DefaultTableCellRenderer head = new DefaultTableCellRenderer();
        head.setHorizontalAlignment(JLabel.CENTER);
        head.setBackground(new Color(252,248,3));
        TABLE_SITUATION.getTableHeader().setDefaultRenderer(head);
        db.getSituation(TABLE_SITUATION);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        CBX_CLIENT = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLE_SITUATION = new javax.swing.JTable();
        BTN_IMPRIMER_SITUATION = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("CLIENT :");

        CBX_CLIENT.setBackground(new java.awt.Color(102, 153, 255));
        CBX_CLIENT.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        CBX_CLIENT.setForeground(new java.awt.Color(51, 51, 51));
        CBX_CLIENT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBX_CLIENT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBX_CLIENTItemStateChanged(evt);
            }
        });
        CBX_CLIENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBX_CLIENTActionPerformed(evt);
            }
        });

        TABLE_SITUATION.setBackground(new java.awt.Color(0, 204, 204));
        TABLE_SITUATION.setForeground(new java.awt.Color(0, 0, 0));
        TABLE_SITUATION.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client", "N° Livraison", "Montan Livraison", "Date livraison", "N° Versement", "Montant Versement", "Date versement"
            }
        ));
        jScrollPane1.setViewportView(TABLE_SITUATION);

        BTN_IMPRIMER_SITUATION.setBackground(new java.awt.Color(0, 153, 153));
        BTN_IMPRIMER_SITUATION.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTN_IMPRIMER_SITUATION.setForeground(new java.awt.Color(0, 0, 0));
        BTN_IMPRIMER_SITUATION.setText("Imprimer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBX_CLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BTN_IMPRIMER_SITUATION)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBX_CLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BTN_IMPRIMER_SITUATION)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBX_CLIENTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBX_CLIENTItemStateChanged
        int id=0;
        Object client=CBX_CLIENT.getSelectedItem();
       if(client != null){
        String cli=client.toString();
        
        db.getSituationByClient(TABLE_SITUATION, cli,cli);
       } 
    }//GEN-LAST:event_CBX_CLIENTItemStateChanged

    private void CBX_CLIENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBX_CLIENTActionPerformed
        
    }//GEN-LAST:event_CBX_CLIENTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Situationclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Situationclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Situationclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Situationclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Situationclient().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Situationclient.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_IMPRIMER_SITUATION;
    private javax.swing.JComboBox<String> CBX_CLIENT;
    private javax.swing.JTable TABLE_SITUATION;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
